name: Unzip File Automatically
on:
  workflow_dispatch:  # 手动触发工作流
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
      
      - name: Unzip the file
        run: unzip zhukongbanAPP4.zip -d ./unzipped_files  # 解压到unzipped_files文件夹
      
      - name: Commit unzipped files
        run: |
          git config --global user.name "Ferry1115"  # 替换成你的GitHub用户名
          git config --global user.email "1303128104@qq.com"  # 替换成你的GitHub绑定邮箱
          git add ./unzipped_files
          git commit -m "Unzip APP1.0.zip"
          git push
